### ISSUE TITLE
My-First-Website review 

### ISSUE THREAD

**Issue by Rumbie-Mudzie7** [natashac18/My-First-Website#1]
Great and impressive work, however(optional) you can improve the following few pointers:
-  Class naming convention, that is, try to give some of your classes names relevant to the particular purpose.
    for example <div id="who"> could be <div id="article-img">
-  When you have more than one CSS file, it is good practice to place them in a stylesheet folder.

**Comment by natashac18** [comment]
Hi Rumbi, Thanks for the useful pointers. I will bare them in mind.
